language: node_js
node_js:
  - 14.5
install:
  - npm install -g codecov
  - npm ci
cache:
  directories:
    - node_modules
services:
  - postgresql
# before_script:
#   - npm install
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
script:
  - npm run test
  # - npm run report-test

