language: node_js
node_js:
  - 14.5
services:
  - postgresql
env:
  - NODE_ENV="test"  
  # - also added on travis
  - TEST_DATABASE_URL='postgres://postgres@localhost/test_db'
before_script:
  - psql -c 'create database test_db;' -U postgres
install:
  - npm install
  - npm install -g codecov
  - npm ci
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
script:
  - npm run test
  # - npm run report-test
  # - npm run report-test


